export const CREATE_MATRIX_SOLVE = 'CREATE_MATRIX_SOLVE';
export const MODIFY_MATRIX_SOLVE = 'MODIFY_MATRIX_SOLVE'; 
export const SOLVE_MATRIX_SOLVE = 'SOLVE_MATRIX_SOLVE';
export const MODIFY_MATRIX_B_SOLVE = 'MODIFY_MATRIX_B_SOLVE'
