export const CREATE_PGRAM_MATRIX = 'CREATE_PGRAM_MATRIX';
export const MODIFY_PGRAM_VECTOR1 = 'MODIFY_PGRAM_VECTOR1';
export const MODIFY_PGRAM_VECTOR2 = 'MODIFY_PGRAM_VECTOR2';
export const SOLVE_PGRAM_MATRIX = 'SOLVE_PGRAM_MATRIX';