 export const CREATE_MATRIX_SCA_MULT = 'CREATE_MATRIX_SCA_MULT';
 export const SCA_MULT_MATRIX = 'SCA_MULT_MATRIX';
 export const MODIFY_SM_MATRIX = 'MODIFY_SM_MATRIX';
 export const MODIFY_SCALE_VALUE = 'MODIFY_SCALE_VALUE';