export const CREATE_CROSS_MATRIX = 'CREATE_CROSS_MATRIX';
export const MODIFY_CROSS_ARRAY1 = 'MODIFY_CROSS_ARRAY1';
export const MODIFY_CROSS_ARRAY2 = 'MODIFY_CROSS_ARRAY2';
export const SOLVE_CROSS_ARRAY = 'SOLVE_CROSS_ARRAY';