export const CREATE_DOT_MATRIX = 'CREATE_DOT_MATRIX';
export const MODIFY_DOT_ARRAY1 = 'MODIFY_DOT_ARRAY1';
export const MODIFY_DOT_ARRAY2 = 'MODIFY_DOT_ARRAY2';
export const SOLVE_DOT_MATRIX = 'SOLVE_DOT_MATRIX';