export const CREATE_MATRIX_MULT = 'CREATE_MATRIX_MULT';
export const MODIFY_MATRIX_MULT_1 = 'MODIFY_MATRIX_MULT_1';
export const MODIFY_MATRIX_MULT_2 = 'MODIFY_MATRIX_MULT_2';
export const SOLVE_MATRIX_MULT = 'SOLVE_MATRIX_MULT';