export const CREATE_LINEAR_MAPPING = 'CREATE_LINEAR_MAPPING';
export const MODIFY_LM_MATRIX = 'MODIFY_LM_MATRIX';
export const MODIFY_LM_VECTOR = 'MODIFY_LM_VECTOR';
export const SOLVE_LINEAR_MAPPING = 'SOLVE_LINEAR_MAPPING';